/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import lb.ComparacaoDasImagens;
import lb.Imagem;
import regras_de_necocios.NCliente;
import regras_de_necocios.MensagemUsuario;
import regras_de_necocios.UsuarioLogin;

/**
 *
 * @author André Rian
 */
public class TelaLogin extends javax.swing.JFrame {

    private CadastroLogin cadastroLogin;
    private UsuarioLogin userAdm, userGrt, userClt, userUsr;
    private boolean usuarioAdmintrador;
    private ComparacaoDasImagens compara;
    private UsuarioLogin usuarioLogin;
    private Imagem imagem;
    private byte[] imagemByte;
    private CadastroCliente cadastroCliente;
    private BufferedImage image1, image2;
    private NCliente sqlLite;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        sqlLite = new NCliente("db/Cadastro.db");
        usuarioLogin = new UsuarioLogin();
        initComponents();
        cbTipoUser.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btBuscaBiometria = new javax.swing.JButton();
        lbImgDigital = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btEntra = new javax.swing.JButton();
        lbCadastra = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        cbTipoUser = new javax.swing.JComboBox<>();
        lbAjuda = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "LOGIN"));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo 3.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario icone.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/key_24.png"))); // NOI18N

        btBuscaBiometria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa2.png"))); // NOI18N
        btBuscaBiometria.setText("Busca...");
        btBuscaBiometria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaBiometriaActionPerformed(evt);
            }
        });

        jLabel6.setText("Imgem do usuário:");

        btEntra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bt entra.png"))); // NOI18N
        btEntra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btEntra.setBorderPainted(false);
        btEntra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntraActionPerformed(evt);
            }
        });

        lbCadastra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCadastra.setForeground(new java.awt.Color(0, 0, 255));
        lbCadastra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add_user.png"))); // NOI18N
        lbCadastra.setText("Cadastre-se");
        lbCadastra.setEnabled(false);
        lbCadastra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCadastraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCadastraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCadastraMouseExited(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        lbAjuda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbAjuda.setForeground(new java.awt.Color(102, 102, 255));
        lbAjuda.setText("Ajuda");
        lbAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAjudaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(lbCadastra))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btEntra, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLimpar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTipoUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btBuscaBiometria, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lbImgDigital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario)
                            .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAjuda)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbAjuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCadastra))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btBuscaBiometria)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbImgDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLimpar)
                    .addComponent(btEntra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoSair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void lbCadastraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCadastraMouseClicked
        // TODO add your handling code here:
        if (usuarioAdmintrador) {
            lbCadastra.setForeground(Color.RED);
            this.dispose();

            if (cadastroLogin == null) {
                cadastroLogin = new CadastroLogin();
            }
            cadastroLogin.setVisible(true);
        }
        usuarioAdmintrador = false;
    }//GEN-LAST:event_lbCadastraMouseClicked

    private void lbCadastraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCadastraMouseEntered
        // TODO add your handling code here:

        lbCadastra.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_lbCadastraMouseEntered

    private void lbCadastraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCadastraMouseExited
        // TODO add your handling code here:
        lbCadastra.setForeground(Color.BLUE);
    }//GEN-LAST:event_lbCadastraMouseExited

    private void btBuscaBiometriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaBiometriaActionPerformed
        // TODO add your handling code here:  
        JFileChooser abrirImagem = new JFileChooser();
        abrirImagem.setDialogTitle("Procura Imagem");
        FileNameExtensionFilter extecaoPermitida = new FileNameExtensionFilter("Imagem", "jpg"); // permitir somente as esteções jpg e png
        abrirImagem.setFileFilter(extecaoPermitida);
        int foiSelecionadoImagem = abrirImagem.showOpenDialog(null);
        if (foiSelecionadoImagem != JFileChooser.APPROVE_OPTION) {

            JOptionPane.showMessageDialog(null, "Você não selecionou nem uma Imagem!");
            return;
        }
        imagem = new Imagem();
        File pegaImagem = abrirImagem.getSelectedFile();
        imagemByte = imagem.coverterImagemEmArryDeByte(pegaImagem);
        Imagem.colocarImagemLabel(lbImgDigital, imagemByte);
    }//GEN-LAST:event_btBuscaBiometriaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        this.txtSenha.setText("");
        this.txtUsuario.setText("");
        this.lbImgDigital.setIcon(null);

    }//GEN-LAST:event_btLimparActionPerformed

    private void btEntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntraActionPerformed
        // TODO add your handling code here:
        try {
            int tamLista = 2;

            if (txtUsuario.getText().isEmpty() || txtSenha.getText().isEmpty()) {
                MensagemUsuario.mensagemAviso("Informe um usuário e senha!");
                return;
            }
            
            usuarioLogin = sqlLite.consultaLogin(txtUsuario.getText().trim());

            if (usuarioLogin == null) {
                MensagemUsuario.mensagemAlerta("Usuário não cadastrado!");
                return;
            }

            if (usuarioLogin.getListUser().size() >= tamLista) {

                if (cbTipoUser.getSelectedItem() == null) {
                    MensagemUsuario.mensagemAviso("Este usuario Tem mais de um tipo!");
                    selecionaUsuario();
                    return;
                }

                if (cbTipoUser.getSelectedIndex() < 0) {
                    MensagemUsuario.mensagemAviso("Selecione um tipo de para usuario!");
                    return;
                }

                comparaTiposUsuario();
                return;

            }
            compararUsuarioCadastrado(usuarioLogin);
        } catch (Exception e) {
            usuarioLogin = null;
            MensagemUsuario.mensagemErro(e.getMessage());
        }


    }//GEN-LAST:event_btEntraActionPerformed

    private void lbAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAjudaMouseClicked
        // TODO add your handling code here:
        MensagemUsuario.mensagemAviso("Caso seja seu primero acesso, utilize o usuário padrão\n "
                + "Usuario: admin\n"
                + "senha: admin");
    }//GEN-LAST:event_lbAjudaMouseClicked

    private void comparaTiposUsuario() {
        switch (cbTipoUser.getSelectedItem().toString()) {
            case "Administrador":
                compararUsuarioCadastrado(userAdm);
                break;
            case "Gerente":
                compararUsuarioCadastrado(userGrt);
                break;
            case "Cliente":
                compararUsuarioCadastrado(userClt);
                break;
            case "Usuario":
                compararUsuarioCadastrado(userUsr);
                break;
            default:

        }
    }

    private void selecionaUsuario() {

        for (UsuarioLogin user : usuarioLogin.getListUser()) {

            switch (user.getTipoDeUsuario()) {
                case "Administrador":
                    userAdm = user;
                    break;
                case "Gerente":
                    userGrt = user;

                    break;
                case "Cliente":
                    userClt = user;
                    break;
                case "Usuario":
                    userUsr = user;
                    break;
                default:

            }
            cbTipoUser.addItem(user.getTipoDeUsuario());
        }
        cbTipoUser.setVisible(true);

    }

    private void compararUsuarioCadastrado(UsuarioLogin user) {

        boolean testeUsuario = comparaString(user.getNomeUsuario(), txtUsuario.getText());
        boolean testeSenha = comparaString(user.getSenha(), txtSenha.getText());

        if (!testeUsuario || !testeSenha) {
            MensagemUsuario.mensagemAlerta("Usuario ou senha invalidos!");
            return;
        }

        if (user.getTipoDeUsuario().trim().equalsIgnoreCase("Administrador") && user.getIDUsuario() == 1) {
            lbCadastra.setEnabled(true);
            usuarioAdmintrador = true;
            MensagemUsuario.mensagemAviso("Bem vindo! " + txtUsuario.getText()
                    + "\n Agora você pode cadastra um novo usuário!");
            return;

        }

        if (user.getTipoDeUsuario().trim().equalsIgnoreCase("Administrador") && user.getIDUsuario() > 1) {

            if (lbImgDigital.getIcon() == null) {
                MensagemUsuario.mensagemAviso("Imagem obrigatoria!");
                return;
            }

            if (!this.resultadoComparacaoImagens(user)) {
                MensagemUsuario.mensagemAlerta("Imagem invalida para este usuário!");
                return;

            }
            lbCadastra.setEnabled(true);
            usuarioAdmintrador = true;
            MensagemUsuario.mensagemAviso("Bem vindo! " + txtUsuario.getText()
                    + "\n Agora você pode cadastra um novo usuário!");
            return;

        }

        if (lbImgDigital.getIcon() == null) {
            MensagemUsuario.mensagemAviso("Imagem obrigatoria!");
            return;
        }

        if (!this.resultadoComparacaoImagens(user)) {
            MensagemUsuario.mensagemAlerta("Imagem invalida para este usuário!");
            return;

        }

        cadastroCliente = new CadastroCliente(user.getTipoDeUsuario(), user.getNomeUsuario());
        cadastroCliente.setVisible(true);
        this.dispose();

    }

    private boolean comparaString(String string1, String string2) {
        if (string1.equals(string2)) {
            return true;
        }

        return false;
    }

    private boolean resultadoComparacaoImagens(UsuarioLogin user) {
        boolean comparacaoImagens = false;
        try {

            imagem = new Imagem();
            compara = new ComparacaoDasImagens();
            String caminhoDaImagem = user.getCaminhoDaImagem() + "/" + user.getNomeDaImagem();
            this.image2 = imagem.coverterParaBufferedImage(caminhoDaImagem);
            this.image1 = imagem.coverterParaBufferedImage(this.imagemByte);
            return comparacaoImagens = compara.comparaImagem(image1, image2);

        } catch (Exception e) {
            return comparacaoImagens;

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
                try {
                    NCliente criarTabela = new NCliente("db/Cadastro.db");
                    criarTabela.criateTable();
                    criarTabela.insertTableUser();
                } catch (Exception ex) {
                    MensagemUsuario.mensagemErro(ex.getMessage());
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscaBiometria;
    private javax.swing.JButton btEntra;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cbTipoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAjuda;
    private javax.swing.JLabel lbCadastra;
    private javax.swing.JLabel lbImgDigital;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
